import os

BEEAPI_VERSION = '0.1.0'

SPEC_SUFFIX = "spec"
TESTS_SUFFIX = "tests"
UNIT_TESTS_SUFFIX = "unit"
FUNCTIONAL_TESTS_SUFFIX = "functional"
LOAD_TESTS_SUFFIX = "load"

PACKAGE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(PACKAGE_DIR)
TESTS_DIR = os.path.join(PROJECT_DIR, TESTS_SUFFIX)
UNIT_TESTS_DIR = os.path.join(TESTS_DIR, UNIT_TESTS_SUFFIX)
FUNC_TESTS_DIR = os.path.join(TESTS_DIR, FUNCTIONAL_TESTS_SUFFIX)
LOAD_TESTS_DIR = os.path.join(TESTS_DIR, LOAD_TESTS_SUFFIX)

DEFAULT_LOGGER_NAME = "BeeAPI"
DEFAULT_INDEX_NAME = "OffIndex"
DEFAULT_DOCKER_TAG = "beeapi"
DEFAULT_API_PORT = 8080
DEFAULT_DICT_PATH = os.path.join(PROJECT_DIR, SPEC_SUFFIX, "off_categories.tsv")

DEFAULT_INDEX_DIR = os.path.join(PROJECT_DIR, "indices")

RAW_COLUMN = "original"
CONTENTS_COLUMN = "contents"
STEMMED_CONTENTS_COLUMN = "stemmed"

INDEXER_FILE = "file"
INDEXER_RAM = "ram"

MAGIC_DIRECT_MATCH_BOOST = 100
MAGIC_SENTENCE_MATCH_BOOST_MULT = 2
MAGIC_SENTENCE_MISMATCH_PENALTY_MULT = 3
MAGIC_WORD_ALIGNMENT_DIFF_PENALTY_MULT = 5
MAGIC_WORD_ALIGNMENT_BOOST_MULT = 5

ENV_MAIN_RUN_LOOPED = "BEEAPI_MAIN_RUN_LOOPED"
USER_QUERY_CACHE_SIZE = 50
PHRASE_QUERY_CACHE_SIZE = 50
